[project]
name = "personal-library-manager"
version = "0.1.0"
description = "A Streamlit-based personal library manager"
author = ["Roohia Bashir <roohiabashir1994@gmail.com>"]
readme = "README.md"
requires-python = ">=3.11"
<<<<<<< HEAD
dependencies = [
    "ruff>=0.9.10",
    "streamlit>=1.43.1",
]

[project.scripts]
personal-library-manager = "personal-library-manager:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
=======
streamlit = "^1.0"
pandas = "^1.0"
dependencies = []
               
[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
>>>>>>> 5ddeee39cc62ebd7b1e9fbadc38d5966a9717888
